# Generated by Django 2.0.2 on 2018-04-19 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('city_guide', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('date', models.DateField()),
                ('id_cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='city_guide.Cart')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=12)),
                ('mail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=500)),
                ('route', models.CharField(max_length=1000)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('id_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='attraction',
            name='category',
        ),
        migrations.RemoveField(
            model_name='attraction',
            name='ticket',
        ),
        migrations.AddField(
            model_name='ticket',
            name='id_attracion',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='city_guide.Attraction'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='id_ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='city_guide.Ticket'),
        ),
        migrations.AddField(
            model_name='attraction_category',
            name='id_attracion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='city_guide.Attraction'),
        ),
        migrations.AddField(
            model_name='attraction_category',
            name='id_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='city_guide.Category'),
        ),
    ]
