# Generated by Django 2.0.2 on 2018-06-01 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city_guide', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='custom_time',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='user_breaks',
            field=models.TextField(default='{}'),
        ),
    ]
