# Generated by Django 2.0.4 on 2018-05-23 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city_guide', '0002_auto_20180517_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='position',
            field=models.IntegerField(default=1),
        ),
    ]
