# Generated by Django 2.0.4 on 2018-04-19 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('city_guide', '0003_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='id_attracion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='city_guide.Attraction'),
        ),
    ]
