# Generated by Django 2.0.2 on 2018-06-01 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('city_guide', '0003_userbreak'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='custom_time',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='user_breaks',
        ),
    ]
