# Generated by Django 2.0.2 on 2018-06-02 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city_guide', '0004_auto_20180601_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='route',
            field=models.TextField(default='{}'),
        ),
    ]
