# Generated by Django 2.0.4 on 2018-05-24 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city_guide', '0004_auto_20180524_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='attraction_order',
            field=models.TextField(default='{}'),
        ),
    ]
