# Generated by Django 2.0.4 on 2018-05-24 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city_guide', '0005_auto_20180524_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='was_order_modified',
            field=models.BooleanField(default=False),
        ),
    ]
