# Generated by Django 2.0.4 on 2018-04-19 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('city_guide', '0005_auto_20180419_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickettype',
            name='discount',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='id_attraction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='city_guide.Attraction'),
        ),
    ]
