# Generated by Django 2.0.4 on 2018-04-20 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('city_guide', '0006_auto_20180419_2007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_path', models.CharField(max_length=250)),
                ('id_attraction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='city_guide.Attraction')),
            ],
        ),
    ]
