# Generated by Django 2.0.4 on 2018-04-20 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('city_guide', '0009_auto_20180420_1900'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attraction',
            options={'get_latest_by': 'name'},
        ),
    ]
