# Generated by Django 2.0.4 on 2018-04-20 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city_guide', '0011_auto_20180420_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='photo_path',
        ),
        migrations.AddField(
            model_name='photo',
            name='photo',
            field=models.ImageField(default=0, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
