# Generated by Django 2.0.4 on 2018-04-20 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('city_guide', '0012_auto_20180420_1946'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'get_latest_by': 'photo'},
        ),
    ]
