# Generated by Django 2.0.4 on 2018-04-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city_guide', '0013_auto_20180420_1959'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={},
        ),
        migrations.AddField(
            model_name='attraction',
            name='main_photo',
            field=models.ImageField(default=0, upload_to='uploads/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attraction',
            name='description',
            field=models.TextField(),
        ),
    ]
