# Generated by Django 2.0.4 on 2018-05-09 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city_guide', '0014_auto_20180426_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(height_field=1280, upload_to='uploads/', width_field=720),
        ),
    ]
